### ISSUE TITLE
Handling XButton1 and XButton2 separately

### ISSUE THREAD

**Issue by nicolasdeory** [macote/Winook#22]
I'm trying to handle click events for both XButtons separately, but `MouseEventArgs` only has a `MessageCode` member which only contains definitions for `XButton` events, but not `XButton1` or `XButton2`. 

[Win32 API](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-xbuttondown) seems to support this through `wParam` and `lParam`, but I can't access those fields from the reference to `MouseMessageEventArgs` (it does have a `Handle`, but I'm not sure where it's pointing to).

It'd be a nice addition to provide support out of the box for these buttons without resorting to using native Win32 methods.

**Comment by macote** [comment]
Hi Nicolás,

Please try the new version. Let me know if you have issues.

Thanks.

**Comment by nicolasdeory** [comment]
Thank you for the super quick implementation. Seems to work fine. I'll reopen if I run into any issues.
