### ISSUE TITLE
Doesn't work with some apps.

### ISSUE THREAD

**Issue by vdvarlamov** [macote/Winook#29]
Unfortunately, it does not work with some applications.
`_process = Process.Start(@"c:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe");`
I really hope this can be fixed. 
Thank you.

**Comment by macote** [comment]
Winook only works with GUI apps. PowerShell is a console app. It doesn't work either with cmd.exe for the same reason.

I did try Winook on [Windows Terminal](https://github.com/microsoft/terminal) and found that it worked. This might be a valid workaround for you.

```csharp
_process = Process.GetProcessesByName("WindowsTerminal")[0];
```
