### ISSUE TITLE
How to attach if multiple instances of an executable?

### ISSUE THREAD

**Issue by cstrife1** [macote/Winook#33]
Do we need to iterate through all processes for an execute and attach to every single one if we want to capture from all? It would be better to use a global hook in that case? Just asking because all global hooks I've tried have severe mouse lag for a few seconds when processing is interrupted, so looking for alternatives.

**Comment by macote** [comment]
Yes, a global hook is required if you can't hook individually to all processes. I would be curious to see if hooking to all processes with Winook would lead to the same lag problems we experience with global hooks. I never tried that before.
